name: Deploy Vault VM

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  PROJECT_ID: "praneeth1211-gcp-pilot"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_JSON }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Deploy Vault VM
        run: |
          cd infrastructure/terraform-vault-vm
          terraform init
          terraform apply -var="project_id=${{ env.PROJECT_ID }}" -auto-approve
          
      - name: Display Vault URL
        run: |
          cd infrastructure/terraform-vault-vm
          VAULT_URL=$(terraform output -raw vault_url)
          echo "======================================================"
          echo "Vault Server successfully deployed!"
          echo "Your Public Vault URL is: $VAULT_URL"
          echo "Your Vault Token is: test-root-token"
          echo "Please update your GitHub Secrets with this URL."
          echo "======================================================"
